
export const MOVEMENT_SPEED = 0.25;
export const ROTATION_SPEED = 0.05;
export const AUDIO_DISTANCE_REF = 2;
export const AUDIO_DISTANCE_MAX = 20;

export const ENVIRONMENTS = {
  nature: {
    name: 'Nature',
    skyColor: '#87CEEB',
    groundColor: '#4CAF50'
  },
  space: {
    name: 'Space',
    skyColor: '#000000',
    groundColor: '#FFFFFF'
  },
  minimal: {
    name: 'Minimal',
    skyColor: '#1e3a8a',
    groundColor: '#1e40af'
  }
};

export const COLORS = [
  '#ef4444', '#f97316', '#f59e0b', '#84cc16', '#10b981', 
  '#06b6d4', '#3b82f6', '#6366f1', '#8b5cf6', '#d946ef', '#f43f5e', '#ffffff', '#1f2937'
];

export const DEFAULT_REACTIONS = ['😂', '💩', '👍', '👎', '❤️'];

export const AVAILABLE_EMOJIS = [
  '😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '🥲', '😊',
  '😇', '🙂', '🙃', '😉', '😌', '😍', '🥰', '😘', '😗', '😙',
  '😚', '😋', '😛', '😝', '😜', '🤪', '🤨', '🧐', '🤓', '😎',
  '🥸', '🤩', '🥳', '😏', '😒', '😞', '😔', 'ww', '😟', '😕',
  '🙁', '☹️', '😣', '😖', '😫', '😩', '🥺', '😢', '😭', '😤',
  '😠', '😡', '🤬', '🤯', '😳', '🥵', '🥶', '😱', '😨', 'uws',
  '😥', '😓', '🤗', '🤔', '🤭', '🤫', '🤥', '😶', '😐', '😑',
  '😬', '🙄', '😯', '😦', '😧', '😮', '😲', '🥱', '😴', '🤤',
  '😪', '😵', '🤐', '🥴', '🤢', '🤮', '🤧', '😷', '🤒', '🤕',
  '🤑', '🤠', '😈', '👿', '👹', '👺', '🤡', '💩', '👻', '💀',
  '☠️', '👽', '👾', '🤖', '🎃', '😺', '😸', '😹', '😻', '😼',
  '😽', '🙀', '😿', '😾', '👋', '🤚', 'Vk', '✋', '🖖', '👌',
  '🤌', '🤏', '✌️', '🤞', '🤟', '🤘', '🤙', '👈', '👉', '👆',
  '🖕', '👇', '☝️', '👍', '👎', '✊', '👊', '🤛', '🤜', '👏',
  '🙌', '👐', '🤲', '🤝', '🙏', '✍️', '💅', '🤳', '💪', '🦾',
  '🦵', '🦿', '🦶', '👣', '👂', '🦻', '👃', '🫀', '🫁', '🧠',
  '🦷', '🦴', '👀', '👁', '👅', '👄', '💋', '🩸', '❤️', '🧡',
  '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '🤎', '💔', '❣️', '💕',
  '💞', '💓', '💗', '💖', '💘', '💝', '🔥', '💥', '✨', '🎉'
];

export const TRANSLATIONS = {
  ru: {
    welcome_title: "Как тебя называть?",
    enter_name: "Введите имя...",
    enter_btn: "Войти",
    friends_list: "Список друзей",
    friends_empty: "У вас пока нет друзей :(",
    profile_settings: "Профиль",
    nickname: "Ник",
    shape: "Форма",
    color: "Цвет",
    logout: "Выход",
    create_room: "Создать комнату",
    open_worlds: "Открытые миры",
    enter_code_placeholder: "Введите код комнаты...",
    enter_room_btn: "Вход",
    online: "Онлайн",
    fans: "Фанатов",
    world: "Мир",
    access: "Доступ",
    private: "Приватная",
    public: "Публичная",
    save: "Сохранить",
    saved: "Сохранено",
    edit: "Редактировать",
    cancel: "Отмена",
    enter_world: "Войти в мир",
    create_title: "Создание комнаты",
    room_name: "Название",
    room_desc: "Описание",
    location: "Локация",
    reactions: "Реакции (5 шт)",
    rules: "Правила",
    rule_screen: "Разрешить раздачу экрана",
    rule_mic: "Запрет откл. микрофона",
    rule_ignore: "Запрет игнорирования",
    solar: "Солнечная",
    lunar: "Лунная",
    office: "Офис",
    settings_title: "Настройки",
    language: "Язык",
    mic: "Микрофон",
    sound: "Звук",
    screen: "Экран",
    config: "Настр.",
    exit: "Выход",
    view_stream: "Нажмите для просмотра",
    add_friend: "Добавить в друзья",
    remove_friend: "Удалить из друзей",
    sure: "Вы уверены?",
    yes: "Да",
    no: "Нет",
    mute: "Игнорировать",
    unmute: "Размутить",
    ignore_forbidden: "Игнор запрещен",
    tp_request: "хочет телепортировать вас.",
    mic_default: "По умолчанию",
    screen_share_hint: "Трансляция экрана",
    select_window: "Выбрать экран / окно",
    browser_hint: "Браузер попросит выбрать окно при нажатии",
    devices_title: "Настройки устройств",
    friends_in_room: "Друзей в комнате",
    copy_id: "Скопировано",
    friends_btn: "Друзья",
    total_btn: "Всего",
    room_nature_title: "Солнечный мир",
    room_nature_desc: "Зеленая травка, голубое небо и солнышко. Идеально для чилла.",
    room_space_title: "Лунная ночь",
    room_space_desc: "Черное небо, снежок и луна. Душевные разговоры.",
    room_minimal_title: "Офис Room8",
    room_minimal_desc: "Классическая переговорная комната с синими стенами."
  },
  en: {
    welcome_title: "What should we call you?",
    enter_name: "Enter name...",
    enter_btn: "Enter",
    friends_list: "Friends List",
    friends_empty: "No friends yet :(",
    profile_settings: "Profile",
    nickname: "Nickname",
    shape: "Shape",
    color: "Color",
    logout: "Logout",
    create_room: "Create Room",
    open_worlds: "Open Worlds",
    enter_code_placeholder: "Enter room code...",
    enter_room_btn: "Join",
    online: "Online",
    fans: "Fans",
    world: "World",
    access: "Access",
    private: "Private",
    public: "Public",
    save: "Save",
    saved: "Saved",
    edit: "Edit",
    cancel: "Cancel",
    enter_world: "Enter World",
    create_title: "Create Room",
    room_name: "Name",
    room_desc: "Description",
    location: "Location",
    reactions: "Reactions (5)",
    rules: "Rules",
    rule_screen: "Allow Screen Share",
    rule_mic: "Forbid Mic Mute",
    rule_ignore: "Forbid Ignoring",
    solar: "Solar",
    lunar: "Lunar",
    office: "Office",
    settings_title: "Settings",
    language: "Language",
    mic: "Mic",
    sound: "Sound",
    screen: "Screen",
    config: "Config",
    exit: "Exit",
    view_stream: "Click to view",
    add_friend: "Add Friend",
    remove_friend: "Remove Friend",
    sure: "Are you sure?",
    yes: "Yes",
    no: "No",
    mute: "Ignore",
    unmute: "Unmute",
    ignore_forbidden: "Ignoring forbidden",
    tp_request: "wants to teleport you.",
    mic_default: "Default",
    screen_share_hint: "Screen Share",
    select_window: "Select Screen / Window",
    browser_hint: "Browser will ask to select window",
    devices_title: "Device Settings",
    friends_in_room: "Friends in room",
    copy_id: "Copied",
    friends_btn: "Friends",
    total_btn: "Total",
    room_nature_title: "Sunny World",
    room_nature_desc: "Green grass, blue sky and sun. Perfect for chilling.",
    room_space_title: "Lunar Night",
    room_space_desc: "Black sky, snow and moon. Soulful conversations.",
    room_minimal_title: "Room8 Office",
    room_minimal_desc: "Classic meeting room with blue walls."
  },
  es: {
    welcome_title: "¿Cómo te llamas?",
    enter_name: "Introduce tu nombre...",
    enter_btn: "Entrar",
    friends_list: "Lista de amigos",
    friends_empty: "Aún no tienes amigos :(",
    profile_settings: "Perfil",
    nickname: "Apodo",
    shape: "Forma",
    color: "Color",
    logout: "Cerrar sesión",
    create_room: "Crear sala",
    open_worlds: "Mundos abiertos",
    enter_code_placeholder: "Código de sala...",
    enter_room_btn: "Unirse",
    online: "En línea",
    fans: "Fans",
    world: "Mundo",
    access: "Acceso",
    private: "Privado",
    public: "Público",
    save: "Guardar",
    saved: "Guardado",
    edit: "Editar",
    cancel: "Cancelar",
    enter_world: "Entrar al mundo",
    create_title: "Crear sala",
    room_name: "Nombre",
    room_desc: "Descripción",
    location: "Ubicación",
    reactions: "Reacciones (5)",
    rules: "Reglas",
    rule_screen: "Permitir compartir pantalla",
    rule_mic: "Prohibir silenciar micro",
    rule_ignore: "Prohibir ignorar",
    solar: "Solar",
    lunar: "Lunar",
    office: "Oficina",
    settings_title: "Ajustes",
    language: "Idioma",
    mic: "Micro",
    sound: "Sonido",
    screen: "Pantalla",
    config: "Config",
    exit: "Salir",
    view_stream: "Clic para ver",
    add_friend: "Añadir amigo",
    remove_friend: "Eliminar amigo",
    sure: "¿Estás seguro?",
    yes: "Sí",
    no: "No",
    mute: "Ignorar",
    unmute: "No ignorar",
    ignore_forbidden: "Ignorar prohibido",
    tp_request: "quiere teletransportarte.",
    mic_default: "Predeterminado",
    screen_share_hint: "Compartir pantalla",
    select_window: "Seleccionar pantalla / ventana",
    browser_hint: "El navegador pedirá seleccionar ventana",
    devices_title: "Ajustes de dispositivos",
    friends_in_room: "Amigos en sala",
    copy_id: "Copiado",
    friends_btn: "Amigos",
    total_btn: "Total",
    room_nature_title: "Mundo Solar",
    room_nature_desc: "Hierba verde, cielo azul y sol. Perfecto para relajarse.",
    room_space_title: "Noche Lunar",
    room_space_desc: "Cielo negro, nieve y luna. Conversaciones profundas.",
    room_minimal_title: "Oficina Room8",
    room_minimal_desc: "Sala de reuniones clásica con paredes azules."
  },
  fr: {
    welcome_title: "Comment t'appelles-tu ?",
    enter_name: "Entrez votre nom...",
    enter_btn: "Entrer",
    friends_list: "Liste d'amis",
    friends_empty: "Pas encore d'amis :(",
    profile_settings: "Profil",
    nickname: "Pseudo",
    shape: "Forme",
    color: "Couleur",
    logout: "Déconnexion",
    create_room: "Créer une salle",
    open_worlds: "Mondes ouverts",
    enter_code_placeholder: "Code de la salle...",
    enter_room_btn: "Rejoindre",
    online: "En ligne",
    fans: "Fans",
    world: "Monde",
    access: "Accès",
    private: "Privé",
    public: "Public",
    save: "Sauvegarder",
    saved: "Sauvegardé",
    edit: "Modifier",
    cancel: "Annuler",
    enter_world: "Entrer",
    create_title: "Création de salle",
    room_name: "Nom",
    room_desc: "Description",
    location: "Lieu",
    reactions: "Réactions (5)",
    rules: "Règles",
    rule_screen: "Partage d'écran autorisé",
    rule_mic: "Interdire muet",
    rule_ignore: "Interdire d'ignorer",
    solar: "Solaire",
    lunar: "Lunaire",
    office: "Bureau",
    settings_title: "Paramètres",
    language: "Langue",
    mic: "Micro",
    sound: "Son",
    screen: "Écran",
    config: "Config",
    exit: "Sortie",
    view_stream: "Cliquer pour voir",
    add_friend: "Ajouter ami",
    remove_friend: "Retirer ami",
    sure: "Êtes-vous sûr ?",
    yes: "Oui",
    no: "Non",
    mute: "Ignorer",
    unmute: "Ne plus ignorer",
    ignore_forbidden: "Ignorer interdit",
    tp_request: "veut vous téléporter.",
    mic_default: "Défaut",
    screen_share_hint: "Partage d'écran",
    select_window: "Choisir écran / fenêtre",
    browser_hint: "Le navigateur demandera de choisir",
    devices_title: "Paramètres périphériques",
    friends_in_room: "Amis présents",
    copy_id: "Copié",
    friends_btn: "Amis",
    total_btn: "Total",
    room_nature_title: "Monde Solaire",
    room_nature_desc: "Herbe verte, ciel bleu et soleil. Parfait pour se détendre.",
    room_space_title: "Nuit Lunaire",
    room_space_desc: "Ciel noir, neige et lune. Conversations profondes.",
    room_minimal_title: "Bureau Room8",
    room_minimal_desc: "Salle de réunion classique aux murs bleus."
  },
  de: {
    welcome_title: "Wie heißt du?",
    enter_name: "Name eingeben...",
    enter_btn: "Eintreten",
    friends_list: "Freundesliste",
    friends_empty: "Noch keine Freunde :(",
    profile_settings: "Profil",
    nickname: "Spitzname",
    shape: "Form",
    color: "Farbe",
    logout: "Abmelden",
    create_room: "Raum erstellen",
    open_worlds: "Offene Welten",
    enter_code_placeholder: "Raumcode...",
    enter_room_btn: "Beitreten",
    online: "Online",
    fans: "Fans",
    world: "Welt",
    access: "Zugang",
    private: "Privat",
    public: "Öffentlich",
    save: "Speichern",
    saved: "Gespeichert",
    edit: "Bearbeiten",
    cancel: "Abbrechen",
    enter_world: "Welt betreten",
    create_title: "Raum erstellen",
    room_name: "Name",
    room_desc: "Beschreibung",
    location: "Ort",
    reactions: "Reaktionen (5)",
    rules: "Regeln",
    rule_screen: "Bildschirmfreigabe erlauben",
    rule_mic: "Stummschalten verbieten",
    rule_ignore: "Ignorieren verbieten",
    solar: "Sonnig",
    lunar: "Mond",
    office: "Büro",
    settings_title: "Einstellungen",
    language: "Sprache",
    mic: "Mikro",
    sound: "Ton",
    screen: "Bildschirm",
    config: "Konfig",
    exit: "Ausgang",
    view_stream: "Zum Ansehen klicken",
    add_friend: "Freund hinzufügen",
    remove_friend: "Freund entfernen",
    sure: "Bist du sicher?",
    yes: "Ja",
    no: "Nein",
    mute: "Ignorieren",
    unmute: "Nicht mehr ignorieren",
    ignore_forbidden: "Ignorieren verboten",
    tp_request: "möchte dich teleportieren.",
    mic_default: "Standard",
    screen_share_hint: "Bildschirm teilen",
    select_window: "Fenster auswählen",
    browser_hint: "Browser fragt nach Fenster",
    devices_title: "Geräteeinstellungen",
    friends_in_room: "Freunde im Raum",
    copy_id: "Kopiert",
    friends_btn: "Freunde",
    total_btn: "Gesamt",
    room_nature_title: "Sonnige Welt",
    room_nature_desc: "Grünes Gras, blauer Himmel und Sonne. Perfekt zum Chillen.",
    room_space_title: "Mondnacht",
    room_space_desc: "Schwarzer Himmel, Schnee und Mond. Tiefe Gespräche.",
    room_minimal_title: "Room8 Büro",
    room_minimal_desc: "Klassischer Besprechungsraum mit blauen Wänden."
  },
  it: {
    welcome_title: "Come ti chiami?",
    enter_name: "Inserisci nome...",
    enter_btn: "Entra",
    friends_list: "Lista amici",
    friends_empty: "Nessun amico ancora :(",
    profile_settings: "Profilo",
    nickname: "Nickname",
    shape: "Forma",
    color: "Colore",
    logout: "Esci",
    create_room: "Crea stanza",
    open_worlds: "Mondi aperti",
    enter_code_placeholder: "Codice stanza...",
    enter_room_btn: "Unisciti",
    online: "Online",
    fans: "Fan",
    world: "Mondo",
    access: "Accesso",
    private: "Privato",
    public: "Pubblico",
    save: "Salva",
    saved: "Salvato",
    edit: "Modifica",
    cancel: "Annulla",
    enter_world: "Entra nel mondo",
    create_title: "Creazione stanza",
    room_name: "Nome",
    room_desc: "Descrizione",
    location: "Luogo",
    reactions: "Reazioni (5)",
    rules: "Regole",
    rule_screen: "Condivisione schermo",
    rule_mic: "Vieta muto",
    rule_ignore: "Vieta ignorare",
    solar: "Solare",
    lunar: "Lunare",
    office: "Ufficio",
    settings_title: "Impostazioni",
    language: "Lingua",
    mic: "Mic",
    sound: "Suono",
    screen: "Schermo",
    config: "Config",
    exit: "Uscita",
    view_stream: "Clicca per vedere",
    add_friend: "Aggiungi amico",
    remove_friend: "Rimuovi amico",
    sure: "Sei sicuro?",
    yes: "Sì",
    no: "No",
    mute: "Ignora",
    unmute: "Non ignorare",
    ignore_forbidden: "Ignorare vietato",
    tp_request: "vuole teletrasportarti.",
    mic_default: "Predefinito",
    screen_share_hint: "Condividi schermo",
    select_window: "Seleziona finestra",
    browser_hint: "Il browser chiederà di scegliere",
    devices_title: "Impostazioni dispositivi",
    friends_in_room: "Amici nella stanza",
    copy_id: "Copiato",
    friends_btn: "Amici",
    total_btn: "Totale",
    room_nature_title: "Mondo Solare",
    room_nature_desc: "Erba verde, cielo blu e sole. Perfetto per rilassarsi.",
    room_space_title: "Notte Lunare",
    room_space_desc: "Cielo nero, neve e luna. Conversazioni profonde.",
    room_minimal_title: "Ufficio Room8",
    room_minimal_desc: "Classica sala riunioni con pareti blu."
  },
  cn: {
    welcome_title: "怎么称呼你？",
    enter_name: "输入名字...",
    enter_btn: "进入",
    friends_list: "好友列表",
    friends_empty: "还没有好友 :(",
    profile_settings: "个人资料",
    nickname: "昵称",
    shape: "形状",
    color: "颜色",
    logout: "登出",
    create_room: "创建房间",
    open_worlds: "开放世界",
    enter_code_placeholder: "输入房间代码...",
    enter_room_btn: "加入",
    online: "在线",
    fans: "粉丝",
    world: "世界",
    access: "访问",
    private: "私有",
    public: "公开",
    save: "保存",
    saved: "已保存",
    edit: "编辑",
    cancel: "取消",
    enter_world: "进入世界",
    create_title: "创建房间",
    room_name: "名称",
    room_desc: "描述",
    location: "位置",
    reactions: "反应 (5个)",
    rules: "规则",
    rule_screen: "允许屏幕共享",
    rule_mic: "禁止静音麦克风",
    rule_ignore: "禁止忽略",
    solar: "阳光",
    lunar: "月夜",
    office: "办公室",
    settings_title: "设置",
    language: "语言",
    mic: "麦克风",
    sound: "声音",
    screen: "屏幕",
    config: "配置",
    exit: "退出",
    view_stream: "点击查看",
    add_friend: "加为好友",
    remove_friend: "删除好友",
    sure: "你确定吗？",
    yes: "是",
    no: "否",
    mute: "忽略",
    unmute: "取消忽略",
    ignore_forbidden: "禁止忽略",
    tp_request: "想传送你。",
    mic_default: "默认",
    screen_share_hint: "屏幕共享",
    select_window: "选择屏幕/窗口",
    browser_hint: "浏览器将询问选择窗口",
    devices_title: "设备设置",
    friends_in_room: "房间里的好友",
    copy_id: "已复制",
    friends_btn: "好友",
    total_btn: "总计",
    room_nature_title: "阳光世界",
    room_nature_desc: "绿草，蓝天和阳光。 适合放松。",
    room_space_title: "月夜",
    room_space_desc: "黑夜，雪和月亮。 深情的对话。",
    room_minimal_title: "Room8 办公室",
    room_minimal_desc: "带有蓝墙的经典会议室。"
  },
  jp: {
    welcome_title: "お名前は？",
    enter_name: "名前を入力...",
    enter_btn: "入る",
    friends_list: "友達リスト",
    friends_empty: "友達はまだいません :(",
    profile_settings: "プロフィール",
    nickname: "ニックネーム",
    shape: "形",
    color: "色",
    logout: "ログアウト",
    create_room: "部屋を作成",
    open_worlds: "オープンワールド",
    enter_code_placeholder: "部屋コード...",
    enter_room_btn: "参加",
    online: "オンライン",
    fans: "ファン",
    world: "世界",
    access: "アクセス",
    private: "プライベート",
    public: "パブリック",
    save: "保存",
    saved: "保存済み",
    edit: "編集",
    cancel: "キャンセル",
    enter_world: "世界に入る",
    create_title: "部屋の作成",
    room_name: "名前",
    room_desc: "説明",
    location: "場所",
    reactions: "リアクション (5つ)",
    rules: "ルール",
    rule_screen: "画面共有を許可",
    rule_mic: "マイクミュート禁止",
    rule_ignore: "無視禁止",
    solar: "ソーラー",
    lunar: "ルナ",
    office: "オフィス",
    settings_title: "設定",
    language: "言語",
    mic: "マイク",
    sound: "音",
    screen: "画面",
    config: "設定",
    exit: "終了",
    view_stream: "クリックして表示",
    add_friend: "友達追加",
    remove_friend: "友達削除",
    sure: "よろしいですか？",
    yes: "はい",
    no: "いいえ",
    mute: "無視する",
    unmute: "無視解除",
    ignore_forbidden: "無視禁止",
    tp_request: "があなたをテレポートさせたいです。",
    mic_default: "デフォルト",
    screen_share_hint: "画面共有",
    select_window: "画面/ウィンドウを選択",
    browser_hint: "ブラウザがウィンドウ選択を求めます",
    devices_title: "デバイス設定",
    friends_in_room: "部屋の友達",
    copy_id: "コピー完了",
    friends_btn: "友達",
    total_btn: "合計",
    room_nature_title: "サニーワールド",
    room_nature_desc: "緑の芝生、青い空、太陽。 リラックスに最適。",
    room_space_title: "ルナナイト",
    room_space_desc: "黒い空、雪、月。 深い会話。",
    room_minimal_title: "Room8 オフィス",
    room_minimal_desc: "青い壁のクラシックな会議室。"
  },
  th: {
    welcome_title: "คุณชื่ออะไร?",
    enter_name: "กรอกชื่อ...",
    enter_btn: "เข้าสู่ระบบ",
    friends_list: "รายชื่อเพื่อน",
    friends_empty: "ยังไม่มีเพื่อน :(",
    profile_settings: "โปรไฟล์",
    nickname: "ชื่อเล่น",
    shape: "รูปร่าง",
    color: "สี",
    logout: "ออกจากระบบ",
    create_room: "สร้างห้อง",
    open_worlds: "โลกเปิด",
    enter_code_placeholder: "รหัสห้อง...",
    enter_room_btn: "เข้าร่วม",
    online: "ออนไลน์",
    fans: "ผู้ติดตาม",
    world: "โลก",
    access: "การเข้าถึง",
    private: "ส่วนตัว",
    public: "สาธารณะ",
    save: "บันทึก",
    saved: "บันทึกแล้ว",
    edit: "แก้ไข",
    cancel: "ยกเลิก",
    enter_world: "เข้าสู่โลก",
    create_title: "สร้างห้องใหม่",
    room_name: "ชื่อ",
    room_desc: "คำอธิบาย",
    location: "สถานที่",
    reactions: "รีแอคชั่น (5)",
    rules: "กฎ",
    rule_screen: "อนุญาตแชร์หน้าจอ",
    rule_mic: "ห้ามปิดไมค์",
    rule_ignore: "ห้ามเพิกเฉย",
    solar: "แสงอาทิตย์",
    lunar: "ดวงจันทร์",
    office: "ออฟฟิศ",
    settings_title: "การตั้งค่า",
    language: "ภาษา",
    mic: "ไมค์",
    sound: "เสียง",
    screen: "หน้าจอ",
    config: "ตั้งค่า",
    exit: "ออก",
    view_stream: "คลิกเพื่อดู",
    add_friend: "เพิ่มเพื่อน",
    remove_friend: "ลบเพื่อน",
    sure: "คุณแน่ใจไหม?",
    yes: "ใช่",
    no: "ไม่",
    mute: "เพิกเฉย",
    unmute: "เลิกเพิกเฉย",
    ignore_forbidden: "ห้ามเพิกเฉย",
    tp_request: "ต้องการเทเลพอร์ตคุณ",
    mic_default: "ค่าเริ่มต้น",
    screen_share_hint: "แชร์หน้าจอ",
    select_window: "เลือกหน้าจอ / หน้าต่าง",
    browser_hint: "เบราว์เซอร์จะถามให้เลือกหน้าต่าง",
    devices_title: "ตั้งค่าอุปกรณ์",
    friends_in_room: "เพื่อนในห้อง",
    copy_id: "คัดลอกแล้ว",
    friends_btn: "เพื่อน",
    total_btn: "รวม",
    room_nature_title: "โลกสดใส",
    room_nature_desc: "หญ้าเขียว ท้องฟ้าคราม และแสงแดด เหมาะสำหรับพักผ่อน",
    room_space_title: "คืนดวงจันทร์",
    room_space_desc: "ท้องฟ้ามืด หิมะ และดวงจันทร์ บทสนทนาที่ลึกซึ้ง",
    room_minimal_title: "ออฟฟิศ Room8",
    room_minimal_desc: "ห้องประชุมคลาสสิกพร้อมผนังสีฟ้า"
  }
};
