
export const MOVEMENT_SPEED = 0.25;
export const ROTATION_SPEED = 0.05;
export const AUDIO_DISTANCE_REF = 2;
export const AUDIO_DISTANCE_MAX = 20;

export const ENVIRONMENTS = {
  day: {
    name: 'Field',
    skyColor: '#87CEEB',
    groundColor: '#4CAF50'
  },
  night: {
    name: 'Winter',
    skyColor: '#000000',
    groundColor: '#FFFFFF'
  },
  office: {
    name: 'Office',
    skyColor: '#1e3a8a',
    groundColor: '#1e40af'
  },
  roofs: {
    name: 'The Roofs',
    skyColor: '#0a0d14',
    groundColor: '#111'
  }
};

export const COLORS = [
  '#ef4444', '#f97316', '#f59e0b', '#84cc16', '#10b981', 
  '#06b6d4', '#3b82f6', '#6366f1', '#8b5cf6', '#d946ef', '#f43f5e', '#ffffff', '#1f2937'
];

// Updated default reactions
export const DEFAULT_REACTIONS = ['👍', '💩', '🤡', '💀', '❤️'];

export const AVAILABLE_EMOJIS = [
  '😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '🥲', '😊',
  '😇', '🙂', '🙃', '😉', '😌', '😍', '🥰', '😘', '😗', '😙',
  '😚', '😋', '😛', '😝', '😜', '🤪', '🤨', '🧐', '🤓', '😎',
  '🥸', '🤩', '🥳', '😏', '😒', '😞', '😔', 'ww', '😟', '😕',
  '🙁', '☹️', '😣', '😖', '😫', '😩', '🥺', '😢', '😭', '😤',
  '😠', '😡', '🤬', '🤯', '😳', '🥵', '🥶', '😱', '😨', 'uws',
  '😥', '😓', '🤗', '🤔', '🤭', '🤫', '🤥', '😶', '😐', '😑',
  '😬', '🙄', '😯', '😦', '😧', '😮', '😲', '🥱', '😴', '🤤',
  '😪', '😵', '🤐', '🥴', '🤢', '🤮', '🤧', '😷', '🤒', '🤕',
  '🤑', '🤠', '😈', '👿', '👹', '👺', '🤡', '💩', '👻', '💀',
  '☠️', '👽', '👾', '🤖', '🎃', '😺', '😸', '😹', '😻', '😼',
  '😽', '🙀', '😿', '😾', '👋', '🤚', 'Vk', '✋', '🖖', '👌',
  '🤌', '🤏', '✌️', '🤞', '🤟', '🤘', '🤙', '👈', '👉', '👉', '👆',
  '🖕', '👇', '☝️', '👍', '👎', '✊', '👊', '🤛', '🤜', '👏',
  '🙌', '👐', '🤲', '🤝', '🙏', '✍️', '💅', '🤳', '💪', '🦾',
  '🦵', '🦿', '🦶', '👣', '👂', '🦻', '👃', '🫀', '🫁', '🧠',
  '🦷', '🦴', '👀', '👁', '👅', '👄', '💋', '🩸', '❤️', '🧡',
  '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '🤎', '💔', '❣️', '💕',
  '💞', '💓', '💗', '💖', '💘', '💝', '🔥', '💥', '✨', '🎉'
];

export const TRANSLATIONS = {
  ru: {
    welcome_title: "Как тебя называть?",
    enter_name: "Введите имя...",
    enter_btn: "Войти",
    friends_list: "Список друзей",
    friends_empty: "У вас пока нет друзей :(",
    profile_settings: "Профиль",
    nickname: "Ник",
    shape: "Форма",
    color: "Цвет",
    logout: "Выход",
    create_room: "Создать комнату",
    open_worlds: "Открытые миры",
    enter_code_placeholder: "Введите код комнаты...",
    search_placeholder: "Поиск...",
    enter_room_btn: "Вход",
    online: "Онлайн",
    fans: "Фанатов",
    world: "Мир",
    access: "Доступ",
    private: "Приватная",
    public: "Публичная",
    save: "Сохранить",
    saved: "В избранном",
    edit: "Редактировать",
    cancel: "Отмена",
    enter_world: "Войти в мир",
    create_title: "Создание комнаты",
    room_name: "Название",
    room_desc: "Описание",
    location: "Локация",
    reactions: "Реакции (5 шт)",
    rules: "Правила",
    rule_screen: "Раздача экрана",
    rule_mic: "Микрофон обязателен",
    rule_ignore: "Запрет игнора",
    custom_rules: "Свои правила",
    add_rule_placeholder: "Например: Не ругаться...",
    add_rule_btn: "Добавить",
    share_link: "Ссылка на комнату",
    copy_link: "Копировать",
    day: "Field",
    night: "Winter",
    office: "Офис",
    roofs: "The Roofs",
    settings_title: "Настройки",
    language: "Язык",
    mic: "Микрофон",
    sound: "Звук",
    screen: "Экран",
    config: "Настр.",
    exit: "Выход",
    view_stream: "Нажмите для просмотра",
    add_friend: "Добавить в друзья",
    remove_friend: "Удалить из друзей",
    sure: "Вы уверены?",
    yes: "Да",
    no: "Нет",
    mute: "Игнорировать",
    unmute: "Размутить",
    ignore_forbidden: "Игнор запрещен",
    tp_request: "хочет телепортировать вас.",
    mic_default: "По умолчанию",
    screen_share_hint: "Трансляция экрана",
    select_window: "Выбрать экран / окно",
    browser_hint: "Браузер попросит выбрать окно при нажатии",
    devices_title: "Настройки",
    friends_in_room: "Друзей в комнате",
    copy_id: "Скопировано",
    friends_btn: "Друзья",
    total_btn: "Всего",
    room_day_title: "Field World",
    room_day_desc: "Зеленая травка, голубое небо и солнышко. Идеально для чилла.",
    room_night_title: "Winter World",
    room_night_desc: "Черное небо, снежок и луна. Душевные разговоры.",
    room_office_title: "Офис Room8",
    room_office_desc: "Базовая комната. Создайте свою приватную комнату.",
    room_roofs_title: "The Roofs",
    room_roofs_desc: "Процедурные небоскребы в густом темном тумане. Осторожно, высоко.",
    create_private_office: "Создать приватный офис",
    legal_agree: "Нажимая «Войти», вы принимаете",
    legal_terms: "Условия использования",
    legal_and: "и",
    legal_privacy: "Политику конфиденциальности",
    legal_modal_terms_title: "Условия использования",
    legal_modal_privacy_title: "Политика конфиденциальности",
    legal_modal_terms_text: "1. Уважение: Будьте вежливы с другими пользователями.\n2. Контент: Запрещен любой незаконный или оскорбительный контент.\n3. Ответственность: Сервис предоставляется «как есть». Мы не несем ответственности за действия пользователей.\n4. Возраст: Использование сервиса разрешено с 13 лет.",
    legal_modal_privacy_text: "1. Данные: Мы не храним личные данные на серверах. Ваши настройки сохраняются локально в браузере.\n2. Соединение: Аудио и видео передаются напрямую между пользователями (P2P).\n3. Cookie: Мы используем локальное хранилище для сохранения ваших предпочтений.",
    sort_popular: "Популярные",
    sort_newest: "Новые",
    sort_online_asc: "Онлайн (Возр.)",
    sort_online_desc: "Онлайн (Убыв.)",
    filter_title: "Фильтры",
    sort_title: "Сортировка",
    filter_min_players: "Мин. игроков",
    filter_rules: "По правилам",
    
    // New Menu Translations
    menu_about: "О сервисе",
    menu_support: "Тех. поддержка",
    menu_careers: "Карьера",
    menu_rules: "Правила платформы",
    menu_privacy: "Конфиденциальность",
    
    about_text: "Room8 — это децентрализованное социальное пространство. Мы верим в открытые связи без серверов, хранящих ваши данные. Версия 15.0.",
    support_text: "Нужна помощь? Присоединяйтесь к нашему Discord или пишите напрямую.",
    career_text: "Мы ищем WebGL-магов и инженеров P2P сетей.",
    career_btn: "Смотреть вакансии"
  },
  en: {
    welcome_title: "What should we call you?",
    enter_name: "Enter name...",
    enter_btn: "Enter",
    friends_list: "Friends List",
    friends_empty: "No friends yet :(",
    profile_settings: "Profile",
    nickname: "Nickname",
    shape: "Shape",
    color: "Color",
    logout: "Logout",
    create_room: "Create Room",
    open_worlds: "Open Worlds",
    enter_code_placeholder: "Enter room code...",
    search_placeholder: "Search...",
    enter_room_btn: "Join",
    online: "Online",
    fans: "Fans",
    world: "World",
    access: "Access",
    private: "Private",
    public: "Public",
    save: "Save",
    saved: "Saved",
    edit: "Edit",
    cancel: "Cancel",
    enter_world: "Enter World",
    create_title: "Create Room",
    room_name: "Name",
    room_desc: "Description",
    location: "Location",
    reactions: "Reactions (5)",
    rules: "Rules",
    rule_screen: "Allow Screen Share",
    rule_mic: "Forbid Mic Mute",
    rule_ignore: "Forbid Ignoring",
    custom_rules: "Custom Rules",
    add_rule_placeholder: "Ex: No swearing...",
    add_rule_btn: "Add",
    share_link: "Room Link",
    copy_link: "Copy",
    day: "Field",
    night: "Winter",
    office: "Office",
    roofs: "The Roofs",
    settings_title: "Settings",
    language: "Language",
    mic: "Mic",
    sound: "Sound",
    screen: "Screen",
    config: "Config",
    exit: "Exit",
    view_stream: "Click to view",
    add_friend: "Add Friend",
    remove_friend: "Remove Friend",
    sure: "Are you sure?",
    yes: "Yes",
    no: "No",
    mute: "Ignore",
    unmute: "Unmute",
    ignore_forbidden: "Ignoring forbidden",
    tp_request: "wants to teleport you.",
    mic_default: "Default",
    screen_share_hint: "Screen Share",
    select_window: "Select Screen / Window",
    browser_hint: "Browser will ask to select window",
    devices_title: "Settings",
    friends_in_room: "Friends in room",
    copy_id: "Copied",
    friends_btn: "Friends",
    total_btn: "Total",
    room_day_title: "Field World",
    room_day_desc: "Green grass, blue sky and sun. Perfect for chilling.",
    room_night_title: "Winter World",
    room_night_desc: "Black sky, snow and moon. Soulful conversations.",
    room_office_title: "Room8 Office",
    room_office_desc: "Base room template. Create your private room.",
    room_roofs_title: "The Roofs",
    room_roofs_desc: "Procedural skyscrapers in thick dark fog. Don't fall.",
    create_private_office: "Create Private Office",
    legal_agree: "By entering, you agree to our",
    legal_terms: "Terms of Service",
    legal_and: "&",
    legal_privacy: "Privacy Policy",
    legal_modal_terms_title: "Terms of Service",
    legal_modal_privacy_title: "Privacy Policy",
    legal_modal_terms_text: "1. Respect: Be kind to others.\n2. Content: No illegal or offensive content.\n3. Liability: The service is provided 'as is'. We are not responsible for user interactions.\n4. Age: You must be 13+ to use this service.",
    legal_modal_privacy_text: "1. Data: We do not store personal data on servers. Your settings are saved locally in your browser.\n2. Connection: Audio and video are transmitted directly between users (P2P).\n3. Cookies: We use local storage for your preferences.",
    sort_popular: "Popular",
    sort_newest: "Newest",
    sort_online_asc: "Online (Asc)",
    sort_online_desc: "Online (Desc)",
    filter_title: "Filters",
    sort_title: "Sort",
    filter_min_players: "Min Players",
    filter_rules: "By Rules",
    
    // New Menu Translations
    menu_about: "About Service",
    menu_support: "Tech Support",
    menu_careers: "Careers",
    menu_rules: "Platform Rules",
    menu_privacy: "Privacy Policy",
    
    about_text: "Room8 is a decentralized, browser-based 3D social space. We believe in open connections without servers storing your data. Version 15.0.",
    support_text: "Need help? Join our community Discord or email us directly.",
    career_text: "We are looking for WebGL wizards and P2P networking engineers.",
    career_btn: "View Open Positions"
  },
  // ... other languages (keeping them concise for this XML block, assuming they exist or fallback to EN/RU keys in Typescript) ...
  es: { /* ... existing ES ... */ 
    share_link: "Enlace", copy_link: "Copiar", custom_rules: "Reglas personalizadas", add_rule_placeholder: "Ej: Sin insultos...", add_rule_btn: "Añadir" 
  },
  fr: { /* ... existing FR ... */ 
    share_link: "Lien", copy_link: "Copier", custom_rules: "Règles perso", add_rule_placeholder: "Ex: Pas d'insultes...", add_rule_btn: "Ajouter"
  },
  de: { /* ... existing DE ... */
    share_link: "Link", copy_link: "Kopieren", custom_rules: "Eigene Regeln", add_rule_placeholder: "Z.B. Keine Beleidigungen...", add_rule_btn: "Hinzufügen"
  },
  it: { /* ... existing IT ... */
    share_link: "Link", copy_link: "Copia", custom_rules: "Regole personalizzate", add_rule_placeholder: "Es: Niente insulti...", add_rule_btn: "Aggiungi"
  },
  cn: { /* ... existing CN ... */
    share_link: "链接", copy_link: "复制", custom_rules: "自定义规则", add_rule_placeholder: "例如：禁止骂人...", add_rule_btn: "添加"
  },
  jp: { /* ... existing JP ... */
    share_link: "リンク", copy_link: "コピー", custom_rules: "カスタムルール", add_rule_placeholder: "例：悪口禁止...", add_rule_btn: "追加"
  },
  th: { /* ... existing TH ... */
    share_link: "ลิงก์", copy_link: "คัดลอก", custom_rules: "กฎเพิ่มเติม", add_rule_placeholder: "เช่น ห้ามด่า...", add_rule_btn: "เพิ่ม"
  }
};
